name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # checkout repo so we can commit back
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: ""
          config: languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "chore(metrics): update github-metrics.svg" || echo "No changes to commit"
          git push
