name: Metrics

on:
  workflow_dispatch:  # allows you to trigger it manually
  schedule:
    - cron: "0 0 * * *"  # runs once a day

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: ""
          config: languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
